%% AEFA-FDB code v1.1.
%% Generated by Dikshit Chauhan, 2025
%% Chauhan, D., Yadav, A., & Cho, S. B. (2025). AEFA-FDB: A score-based artificial electric field algorithm
%% for optimal reactive power dispatch problem with renewable and load demand uncertainties.
%% Applied Soft Computing, 113292

%% Main function for using AEFA-FDB algorithm.
clear all;clc
for i=9
    dim=30;
    rng('default');
    rng(1);rand('seed', sum(100*clock));
    N=30;
    max_it=1000; Max_iteration=max_it;
    FCheck=1; R=1;
    tag=1; % 1: minimization, 0: maximization
    Function_name=i
    for run=1:1
        [Fbest,Lbest,BestValues,MeanValues]=AEFA_FDB(Function_name,N,max_it,FCheck,tag,R,dim);Fbest
    end
end
%%